# 
FROM python

LABEL maintainer="Ladipo Ipadeola" maintainer_email="ipadeolaoladipo@outlook.com"

ENV key=value

WORKDIR /the/workdir/path

ADD source dest

COPY source dest

EXPOSE port

RUN command

CMD [ "executable" ]

ENTRYPOINT [ "python"," -m streamlit",  "run" ,"app.py"] 
